---
name: DiplomProject
configs:
    Debug: debug
    AppStore: release
packages:
    UI:
      path: UI
    Core:
      path: Core
    Localization:
      path: Localization
    Services:
      path: Services
    FlowStacks:
      url: https://github.com/johnpatrickmorgan/FlowStacks.git
      from: 0.3.0
    ComposableArchitecture:
      url: https://github.com/pointfreeco/swift-composable-architecture.git
      from: 0.49.2
    TCACoordinators:
      url: https://github.com/johnpatrickmorgan/TCACoordinators.git
      from: 0.3.0
    SnapKit:
      url: https://github.com/SnapKit/SnapKit.git
      from: 5.0.1
options:
    createIntermediateGroups: true
    developmentLanguage: en
    usesTabs: false
    indentWidth: 4
    tabWidth: 4
    deploymentTarget:
      iOS: '16.0'
    generateEmptyDirectories: true
    defaultConfig: Debug
    groupSortPosition: top
    groupOrdering:
        - order: [DiplomProject]
settings:
    base:
      MARKETING_VERSION: '1.0'
      SPRINT_NUMBER: 1
      SPRINT_BUILD_NUMBER: 0
      CURRENT_PROJECT_VERSION: 0
      VERSIONING_SYSTEM: apple-generic
      CODE_SIGN_STYLE: Manual
      SUPPORTS_MACCATALYST: 'NO'
    configs:
      Debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      AppStore:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
        VALIDATE_PRODUCT: true

в:
   DiplomProject:
    type: application
    platform: iOS
    sources:
      - DiplomProject/Sources
      - path: DiplomProject/Resources
    dependencies:
      - package: UI
      - package: FlowStacks
      - package: Core
      - package: Services
      - package: Localization
      - package: ComposableArchitecture
      - package: TCACoordinators
      - package: SnapKit
    settings:
        base:
          INFOPLIST_FILE: DiplomProject/Resources/Info.plist
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: false
          TARGETED_DEVICE_FAMILY: 1
        configs:
          Debug:
            CODE_SIGN_IDENTITY: iPhone Developer
            DEVELOPMENT_TEAM: ttt
            PROVISIONING_PROFILE_SPECIFIER: ttt
            PRODUCT_BUNDLE_IDENTIFIER: ttt
            PRODUCT_NAME: Diplom
            DISPLAY_NAME: "$(PRODUCT_NAME) $(CONFIGURATION) $(CURRENT_PROJECT_VERSION)"
          AppStore:
            CODE_SIGN_IDENTITY: iPhone Distribution
            DEVELOPMENT_TEAM: ttt
            PRODUCT_BUNDLE_IDENTIFIER: diplom
            PROVISIONING_PROFILE_SPECIFIER: diplom
            PRODUCT_NAME: Diplom
            DISPLAY_NAME: "$(PRODUCT_NAME)"
    preBuildScripts:
        - path: Scripts/swiftgen.sh
          basedOnDependencyAnalysis: false

targetTemplates:
  BaseTarget:
    platform: iOS
    sources:
      - ${target_name}/Sources
      - ${target_name}/Resources
  Framework:
    templates:
      - BaseTarget
    type: framework
    settings:
      base:
        INFOPLIST_FILE: ${target_name}/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: diplom.${target_name}
        TARGETED_DEVICE_FAMILY: '1'
schemes:
  Debug:
    templates:
    - ConfigBasedScheme
    run:
      config: Debug
  AppStore:
    templates:
    - ConfigBasedScheme
    run:
      config: AppStore

schemeTemplates:
  ConfigBasedScheme:
    build:
      targets:
        DiplomProject: all
    run:
      сonfig: ${scheme_name}
    test:
      config: ${scheme_name}
    profile:
      config: ${scheme_name}
    analyze:
      config: ${scheme_name}
    archive:
      config: ${scheme_name}
